/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as RoutinesIndexRouteImport } from './routes/routines.index'
import { Route as ChatIndexRouteImport } from './routes/_chat/index'
import { Route as RoutinesIdRouteImport } from './routes/routines.$id'
import { Route as ChatChatIdRouteImport } from './routes/_chat/chat.$id'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutinesIndexRoute = RoutinesIndexRouteImport.update({
  id: '/routines/',
  path: '/routines/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const RoutinesIdRoute = RoutinesIdRouteImport.update({
  id: '/routines/$id',
  path: '/routines/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatChatIdRoute = ChatChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => ChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/sign-in': typeof SignInRoute
  '/routines/$id': typeof RoutinesIdRoute
  '/routines/': typeof RoutinesIndexRoute
  '/chat/$id': typeof ChatChatIdRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/routines/$id': typeof RoutinesIdRoute
  '/': typeof ChatIndexRoute
  '/routines': typeof RoutinesIndexRoute
  '/chat/$id': typeof ChatChatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/routines/$id': typeof RoutinesIdRoute
  '/_chat/': typeof ChatIndexRoute
  '/routines/': typeof RoutinesIndexRoute
  '/_chat/chat/$id': typeof ChatChatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sign-in' | '/routines/$id' | '/routines/' | '/chat/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/sign-in' | '/routines/$id' | '/' | '/routines' | '/chat/$id'
  id:
    | '__root__'
    | '/_chat'
    | '/sign-in'
    | '/routines/$id'
    | '/_chat/'
    | '/routines/'
    | '/_chat/chat/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  SignInRoute: typeof SignInRoute
  RoutinesIdRoute: typeof RoutinesIdRoute
  RoutinesIndexRoute: typeof RoutinesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routines/': {
      id: '/routines/'
      path: '/routines'
      fullPath: '/routines/'
      preLoaderRoute: typeof RoutinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/routines/$id': {
      id: '/routines/$id'
      path: '/routines/$id'
      fullPath: '/routines/$id'
      preLoaderRoute: typeof RoutinesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/chat/$id': {
      id: '/_chat/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatChatIdRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatIndexRoute: typeof ChatIndexRoute
  ChatChatIdRoute: typeof ChatChatIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatIndexRoute: ChatIndexRoute,
  ChatChatIdRoute: ChatChatIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  SignInRoute: SignInRoute,
  RoutinesIdRoute: RoutinesIdRoute,
  RoutinesIndexRoute: RoutinesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
